services:
  - type: web
    name: psi-09-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PSI09_API_URL
        sync: false

