services:
  - type: web
    name: playwright-whatsapp-bot
    runtime: node
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
