services:
  - type: web
    name: psi09-whatsapp-bot
    env: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome --path=/opt/render/.cache/puppeteer
    startCommand: node server.js
    plan: free
